### ISSUE TITLE
API Blueprint 1A

### ISSUE THREAD

**Issue by fosteman** [appwrite/sdk-generator#1]
Howdy @eldadfux !
I noted this description document to be in future sight of appwrite's development cycles.

Truth be told, I'd be doing this for the first time - getting along with PHP - but I am confident I can befriend `api-blueprint` and `sdk-generator` communicating with you.

You think this document is relevant to be realized at present ?

**Comment by eldadfux** [comment]
This something that can definitely benefit this project. Truth be told we are more focused on getting help with adding new templates for more languages. But I don't see any reason to not go forward with both direction.

You can reach out on our Appwrite community on gitter:
https://gitter.im/appwrite/community
