### ISSUE TITLE
[Flutter] Support for Null-safety

### ISSUE THREAD

**Issue by Sameerkash** [appwrite/sdk-generator#134]
Null -safety for Dart is now available in the stable channel. 

I'm planning to use appwrite for one of my projects, it'd be great if there's null safety support. 

Although I'm not familiar with the generator approach, I'm happy to raise a PR for null-safety with some guidance.

**Comment by eldadfux** [comment]
@Sameerkash I think @lohanidamodar has just create a PR a few hours before you opened this issue: https://github.com/appwrite/sdk-generator/pull/126 😃

**Comment by lohanidamodar** [comment]
@Sameerkash we are almost done with our implementation for Null safety release #148 
We would love your help testing, the current version is available in our git repository
https://github.com/appwrite/sdk-for-flutter/tree/feat-null-safety-new

You can use the dependency directly from github under dependencies in your pubspec.yaml file for now for testing
```
appwrite:
  git:
    url: https://github.com/appwrite/sdk-for-flutter.git
    ref: feat-null-safety-new
```

Do provide us feedback if you have any suggestions, issues or improvements.

Thank you

**Comment by Sameerkash** [comment]
@lohanidamodar So sorry, currently I'm stuck with a lot of work, I'm unsure if I'll be able to test, but I'll definitely report an issue if I encounter anything

**Comment by lohanidamodar** [comment]
Null safety has been released 
https://pub.dev/packages/appwrite/versions/0.5.0-dev.1
