### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by TorstenDittmann** [appwrite/sdk-generator#142]
Based on [this comment](https://www.reddit.com/r/selfhosted/comments/mb6z91/self_hosted_firebase_alternative/gryxyoj?utm_medium=android_app&utm_source=share&context=3) we should investigate how compatible our Web SDK is with react-native and if we need a react-native specific SDK.

**Comment by trydalch** [comment]
If you had support for react native, I would be using this right now.

**Comment by lohanidamodar** [comment]
@TorstenDittmann Will the refactored web SDK work well with ReactNative? I am not sure about oAuth implementation, apart from that it should work. Would be happy to test once we release it.

**Comment by TorstenDittmann** [comment]
@lohanidamodar It would be easily imported and recognized by the bundler.

Could be worth a try 🤔

**Comment by TorstenDittmann** [comment]
Just run a small test with https://expo.io/

Everything except OAuth seems to work 👍🏻

**Comment by lohanidamodar** [comment]
@TorstenDittmann is this still relevant?

**Comment by stnguyen90** [comment]
Closing as we should track specific problems in https://github.com/appwrite/sdk-for-web
