### ISSUE TITLE
Postman compatible import

### ISSUE THREAD

**Issue by gusgeek** [appwrite/sdk-generator#143]
Hello! When will they be compatible with Postman?

**Comment by kodumbeats** [comment]
Hi! We generate both OpenAPI 3 and Swagger 2 API specifications, which we publish on our website. I've included links for the *Client* and *Server* OpenAPI specifications, which you can [import into Postman](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/) as needed:

https://appwrite.io/specs/open-api3?platform=client
https://appwrite.io/specs/open-api3?platform=server

**Comment by itishermann** [comment]
> Hi! We generate both OpenAPI 3 and Swagger 2 API specifications, which we publish on our website. I've included links for the _Client_ and _Server_ OpenAPI specifications, which you can [import into Postman](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/) as needed:
> 
> https://appwrite.io/specs/open-api3?platform=client https://appwrite.io/specs/open-api3?platform=server

Hi there!
Looks like the links are broken (404).
Are there any alternative ?

**Comment by TorstenDittmann** [comment]
> > Hi! We generate both OpenAPI 3 and Swagger 2 API specifications, which we publish on our website. I've included links for the _Client_ and _Server_ OpenAPI specifications, which you can [import into Postman](https://learning.postman.com/docs/integrations/available-integrations/working-with-openAPI/) as needed:
> > https://appwrite.io/specs/open-api3?platform=client https://appwrite.io/specs/open-api3?platform=server
> 
> Hi there! Looks like the links are broken (404). Are there any alternative ?

https://github.com/appwrite/appwrite/tree/master/app/config/specs

Here is the new location 👍🏻
