### ISSUE TITLE
Idiomatic way to parse conditional headers

### ISSUE THREAD

**Issue by christyjacob4** [appwrite/sdk-generator#171]
In the [CLI templates](https://github.com/appwrite/sdk-generator/pull/170/files#diff-1f6f304940541af429979e9c9055117c72d30287d4637297afbdf54eafb263c6R43), we use `if` conditions to conditionally render headers. This is neither clean nor scalable. 

We need to come up with a better convention to allow conditional parsing of the spec files. 
This can be done either by some modifications in the spec or by using a better logic on the client side.

**Comment by lohanidamodar** [comment]
@christyjacob4 is this still relevant? if yes let's discuss soon.

**Comment by lohanidamodar** [comment]
@christyjacob4 closing this as we switched to NodeJS CLI. Please re-open if this is still relevant.
