### ISSUE TITLE
Add Java Support

### ISSUE THREAD

**Issue by PedroCisnerosSantana** [appwrite/sdk-generator#24]
We need help adding Java templates to this project to allow easy generation of Java SDKs for Appwrite server.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

**Comment by PedroCisnerosSantana** [comment]
I will work on it @eldadfux

**Comment by eldadfux** [comment]
👌🏻

**Comment by Dmunch04** [comment]
Yay

**Comment by JarFiles** [comment]
Is there an eta when this could be finished? I really need Java support :)

**Comment by kutear** [comment]
two years passed!  java/kotlin still not be supported.

**Comment by eldadfux** [comment]
> two years passed! java/kotlin still not be supported.

We're trying to do as best as we can. We expect to push this forward in the next few weeks.

**Comment by kutear** [comment]
> > two years passed! java/kotlin still not be supported.
> 
> We're trying to do as best as we can. We expect to push this forward in the next few weeks.

thanks, i will be grad to wait for it.

**Comment by abnegate** [comment]
@eldadfux If you need support on this I'd be happy to finish up what's there (most can be ported from Kotlin #150)

**Comment by christyjacob4** [comment]
@abnegate that would be amazing :D

**Comment by abnegate** [comment]
@christyjacob4 On it now

**Comment by eldadfux** [comment]
We now have officially released both our SDKs for Android and Kotlin! Thanks @abnegate for the awesome work!
* https://github.com/appwrite/sdk-for-android
* https://github.com/appwrite/sdk-for-kotlin

**Comment by seemantshekhar43** [comment]
@eldadfux do we have java sdk ?

**Comment by sergeycherepanov** [comment]
@eldadfux what about the native java support?

**Comment by Walzen665** [comment]
Java in 2025? Pls!
