### ISSUE TITLE
Email Verification Returns Empty if False

### ISSUE THREAD

**Issue by fidst** [appwrite/sdk-generator#244]
https://github.com/appwrite/sdk-for-php/blob/981134a47e3bbcb1d1e17b1b36a22254a14530d4/src/Appwrite/Services/Users.php#L338

https://discord.com/channels/564160730845151244/564161373148414012/879169819814019112

When attempting to use the PHP server sdk, and sending:
 $result = $users->updateVerification([USERID], [FALSE]);

It returns "missing required parameter for emailverification"

**Comment by eldadfux** [comment]
@TorstenDittmann can we close this issue?
