### ISSUE TITLE
Flutter creating OAuth session returning error 

### ISSUE THREAD

**Issue by Silfalion** [appwrite/sdk-generator#253]
The OAuth session creation returns an error at this line on Flutter:

https://github.com/appwrite/sdk-generator/blob/4be966578e99d5545f96ef8c3ba35403920cc5b3/templates/flutter/lib/src/client_io.dart.twig#L193

This should be because the url isn´t parse, so added that line from the previous commit in this pull request:

https://github.com/appwrite/sdk-generator/pull/252

**Comment by lohanidamodar** [comment]
@Silfalion This should already be resolved 
https://github.com/appwrite/sdk-generator/blob/f42e70737d3b63fb8440111022c9509529a16479/templates/flutter/lib/src/client_io.dart.twig#L193

If not please reopen the issue and provide more information on the Error received and how to reproduce the error.
