### ISSUE TITLE
flutter_web_Auth should be updated

### ISSUE THREAD

**Issue by prooshani** [appwrite/sdk-generator#257]
Hey great AppWrite team...

Recently, I have updated my Flutter SDK and after that my app returns failed on run because of a package outdated which I did not imported by myself. Flutter_web_auth 0.3.0 package is the culprit.
It is turned out that appwrite 1.0.2 is using flutter_web_auth 0.3.0 which is not compatible with new flutter sdk.
Therefore, I have manually imported flutter_web_auth 0.3.1 and the issue has gone but it looks necessary to update the appwrite package to get newer version of this package too.

Hope it helps somebody here.
Thanks

**Comment by lohanidamodar** [comment]
@prooshani The recent version (2.0.1), this should be updated! If the issue still persist feel free to reopen the issue.
