### ISSUE TITLE
path generation is wrong in python

### ISSUE THREAD

**Issue by wentzlau** [appwrite/sdk-generator#26]
The generated python sdk does not create api path correctly in the generated functions.

From database.py
```python
def delete_collection(self, collection_id):
        """Delete Collection"""

        params = {}
        path = '/database/{collectionId}'
        path.replace('{collectionId}', collection_id) 
```
The problem is that path.replace returns a new string it does not modify the source.

It is should be
```python
path = '/database/{collectionId}'
path = path.replace('{collectionId}', collection_id)
```

From python version 3.6 string interpolation is supported and the path could be created like this
```python
path = f'/database/{collection_id}'
```

**Comment by eldadfux** [comment]
Added a fix. Still with support for python 3.5, but we can change that later.

**Comment by wentzlau** [comment]
I have tried v 0.4.0 with the newly generated sdk and it works now.
