### ISSUE TITLE
Add exception handling to python client

### ISSUE THREAD

**Issue by wentzlau** [appwrite/sdk-generator#27]
In the python client the client.call function returns the response object.
All callers should then check the status of the response and get the json response.

I think that it would be better to change line  65 in client.py.twig

return response 

To

response.raise_for_status()
return response.json()

This will raise exceptions for all non 2xx responses and return the json response

**Comment by eldadfux** [comment]
@PedroCisnerosSantana this should also help you.

Anyway, i'll add it right now and send you guys to review the commit.

**Comment by eldadfux** [comment]
@wentzlau @PedroCisnerosSantana if this seems ok, I'll release a new pip version:
https://github.com/appwrite/sdk-generator/commit/45880d72795e1fb7dd5e791fe71f1c6bf7494e04

**Comment by wentzlau** [comment]
It looks alright

**Comment by eldadfux** [comment]
Released version 0.3.0 of the Python SDK 🎉
![image](https://user-images.githubusercontent.com/1297371/71362948-41f82d00-25a0-11ea-88a6-f76e860e80d0.png)

**Comment by wentzlau** [comment]
Discovered that empty response generates an exception as there is no json data.
This occurs when calling Auth.login

The last lines should be:

response.raise_for_status()
try:
    return response.json()
except ValueError:
    return None

I think that this should be last resort all api calls should return json data.

**Comment by eldadfux** [comment]
@wentzlau I am working on a fix, also adding the Python SDK to our new automated tests layer to make sure this kind of things don't repeat again.
