### ISSUE TITLE
Implement Godot SDK

### ISSUE THREAD

**Issue by Meldiron** [appwrite/sdk-generator#276]
Your task is to implement Godot SDK using our SDK generator. Please take a look at existing generators for other languages to have a clearer vision of how to do it. If you really struggle to implement it into the sdk-generator, it's fine to implement it as a separate repository and ignore our generator. Please give it a try and let us know if we need to switch to a separate repo 🙏

---

If you need any help, reach out to us on our [Discord server](https://discord.gg/GSeTUeA).

This issue is reserved for `Fenix` from Discord.

**Happy Appwriting!**

**Comment by fenix-hub** [comment]
Thank you for assigning me this task. I'll make sure to follow your resources. :rocket:

**Comment by Meldiron** [comment]
@fenix-hub Assigned it to you! All the best 🚀

**Comment by aabmets** [comment]
@Meldiron Why is this issue still open for Hacktoberfest 2022?

**Comment by stnguyen90** [comment]
@aabmets, looks like this wasn't closed after the PR was merged. I'll close it now and we can revisit if there's another feature request for updated/official SDK.
