### ISSUE TITLE
Ruby SDK: exception on dependency requirement

### ISSUE THREAD

**Issue by foxy-eyed** [appwrite/sdk-generator#281]
Caught exception:
```
<internal:/Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- mime/types (LoadError)
```
on library load
```
require 'appwrite'
```

This happens because lib `mime-types` is used in runtime, but not included to `gemspec` as a runtime dependency.

## How to reproduce:

1. Check if dependency `mime-types` installed globally for current Ruby version:
```
$ gem list
```
and uninstall if present (to simulate 'clean' ruby env):
```
gem uninstall mime-types
```
2. Create new app dir and add `Gemfile` with `appwrite` gem:
```
$ mkdir my_app
$ cd my_app
$ echo "source 'https://rubygems.org'\n\nruby '~> 3.0'\n\ngem 'appwrite', '~> 2.4'"  > Gemfile
```

3. Run `$ bundle install`

4. Run irb and execute:
```
require 'appwrite'
```

Trace:
<img width="1032" alt="Screenshot 2021-10-12 at 17 45 37" src="https://user-images.githubusercontent.com/19491749/137012933-f8dad29d-c59d-42d9-9d30-a60e3caecc87.png">

## Expected behaviour
Running `$ bundle install` must add all necessary dependencies to user's system for lib to work (and not to require manual installation).

**Comment by lohanidamodar** [comment]
@foxy-eyed Closing this as resolved based on the comment on the PR, if it still exists, feel free to reopen.
