### ISSUE TITLE
Ruby SDK: Client raises TypeError when API responds with 204

### ISSUE THREAD

**Issue by jacobprudhomme** [appwrite/sdk-generator#289]
Hey! Just ran into an issue already open in appwrite/sdk-for-ruby#6 by @foxy-eyed and thought I should post it here, since that repo is read-only. Here's the body of the issue as it appears in the original:

> Hi! SDK raises exception when calling `Appwrite::Database#delete_document` because API endpoint responds with `204 No Content` without body, but `Appwrite::Client` expects JSON and tries to parse it.
> 
> Ruby version: `3.0.2` SDK version: `2.4.0`
> 
> Trace:
> 
> ```
> /Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `initialize': no implicit conversion of nil into String (TypeError)
> 	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `new'
> 	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/3.0.0/json/common.rb:216:in `parse'
> 	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/client.rb:110:in `fetch'
> 	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/client.rb:67:in `call'
> 	from /Users/anna/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/appwrite-2.4.0/lib/appwrite/services/database.rb:294:in `delete_document'
> ```
> 
> I suppose it is common problem for all `DELETE` endpoints such as `Appwrite::Database#delete_document`, `Appwrite::Storage#delete_file`, `Appwrite::Storage#delete_collection`
> 
> I could try to fix and open PR if it's ok)

The issue happens at https://github.com/appwrite/sdk-for-ruby/blob/master/lib/appwrite/client.rb#L110. My guess is that the case where `response.class == Net::HTTPNoContent` should be handled separately (or maybe not at all?) before getting to this point.

**Comment by eldadfux** [comment]
Fix was merged and will be released in the next Ruby SDK version.
