### ISSUE TITLE
🐛 Bug Report: [Android SDK] Serialization Engine

### ISSUE THREAD

**Issue by SebastianTMo** [appwrite/sdk-generator#315]
### 👟 Reproduction steps

When using a serialization engine other than Gson in your app (for example KotlinXSerialization) the annotations to your data classes are not recognised by the Gson serialization engine used by the SDK.

### 👍 Expected behavior

Propper object parsing.

I think the best solution for this problem might be choosing the serialization engine beforehand but happy to hear your oppinions on this one.

### 👎 Actual Behavior

The problem occures when casting `RealtimeResponseEvents.payload` within the `subscribe`-functions (using the `payloadType` parameter). The SDK will try to cast the `payload`-object using Gson and will fail for `$id` and `$permission` (as you need to annotate them propperly to be parsed due to the $-sign). This will also occur, when your data class parameter names will differ from the parameter names in the json-String.

Current Workaround:
Double-Annotation of the problematic parameters.

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by christyjacob4** [comment]
@abnegate please take a look at this
