### ISSUE TITLE
🚀 Feature: A way to disable self-signed certificate restriction

### ISSUE THREAD

**Issue by miyavsu-limited** [appwrite/sdk-generator#329]
### 🔖 Feature description

Appwrite client does not work in Jest environment when used with local docker images. Instead it throws an error: `reason: self signed certificate`.  There should be a way to disable Appwrite client's self signed certificate restriction for testing purposes.

### 🎤 Pitch

An error is thrown when Appwrite client is used in Jest environment:

```
    AppwriteException: request to https://localhost/v1/database/collections/6180e6efb14df/documents failed, reason: self signed certificate

      at Appwrite.<anonymous> (../../node_modules/appwrite/src/sdk.ts:419:19)
          at Generator.throw (<anonymous>)
      at rejected (../../node_modules/appwrite/node_modules/tslib/tslib.es6.js:74:65)
```

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
For testing you can always use Appwrite on `http` instead of `https`. You can also check the `_APP_OPTIONS_FORCE_HTTPS` env variable that allows you to disable the `https` redirect: https://appwrite.io/docs/environment-variables#general.

**Comment by miyavsu-limited** [comment]
Disabling https solved this problem.
