### ISSUE TITLE
Replace deprecated Node.js request library

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#33]
The request library has been marked as deprecated. We need to replace it with a valid alternative.

More information and alternative libraries are listed here:
https://github.com/request/request/issues/3143

**Comment by meysam81** [comment]
Hey there,

I have zero experience using PHP. I was looking for a way to test my changes against the current code and I couldn't find one, to see if it breaks anything or not. Can you guide me please?

**Comment by eldadfux** [comment]
You will need composer installed (php equivalent to npm).

When composer is installed, run:

```bash
composer install
```

and then run:

```
vendor/bin/phpunit
```

to execute all the tests

**Comment by eldadfux** [comment]
This issue is open for grab.

**Comment by PineappleIOnic** [comment]
Can I try changing the library?

**Comment by eldadfux** [comment]
@PineappleIOnic yes please 🙏🏻

**Comment by PineappleIOnic** [comment]
#66 has been merged, I'm pretty sure this issue can be closed 😄

**Comment by eldadfux** [comment]
@PineappleIOnic I'm leaving it open as a reminder to publish the new SDK version :)

**Comment by PineappleIOnic** [comment]
Ah, alright 👍

**Comment by eldadfux** [comment]
Didn't forget about this we'll probably release in 1-2 weeks max! Adding myself a reminder!

**Comment by eldadfux** [comment]
Forgot to update here, but this has been released on the latest version together with the release of Appwrite 0.7. Thank for the help @PineappleIOnic 👏🏻
