### ISSUE TITLE
🐛 Bug Report: [Android] [Realtime Feature] Subscribing to a cloud function execution - Missing ID and read parameters when using the Execution class as payloadType 

### ISSUE THREAD

**Issue by SebastianTMo** [appwrite/sdk-generator#345]
### 👟 Reproduction steps

[Appwrite Version 0.12]
[Android SDK Version 0.3.2]

Try to subscribe to a `Cloud Function Execution` using the Execution class as payloadType, process the payload data in the callback function.

### 👍 Expected behavior

Having all relevant data available as per:
https://appwrite.io/docs/models/execution

### 👎 Actual Behavior

`ID ` and `read` paramenters are null.

Root cause seems to be missing annotations for below two lines:

https://github.com/appwrite/sdk-for-android/blob/7c78fa58bdc97b913a959d6f326874423855f739/library/src/main/java/io/appwrite/models/Execution.kt#L11

and 

https://github.com/appwrite/sdk-for-android/blob/7c78fa58bdc97b913a959d6f326874423855f739/library/src/main/java/io/appwrite/models/Execution.kt#L17

Workaround: Using a custom data class with the appropriate annotations, e.g.:
```
import com.google.gson.annotations.SerializedName

data class ExecutionObjectResponse(
    val dateCreated: Long,
    val exitCode: Long,
    val functionId: String,
    @SerializedName("\$id")
    val id: String,
    @SerializedName("\$read")
    val read: List<String>,
    val status: String,
    val stderr: String,
    val stdout: String,
    val time: Double,
    val trigger: String
)
```

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by abnegate** [comment]
Fixed in version 0.3.3 🥳
