### ISSUE TITLE
🐛 Bug Report: Query class type definition missing

### ISSUE THREAD

**Issue by vladmit3** [appwrite/sdk-generator#348]
### 👟 Reproduction steps

`
import sdk from "node-appwrite";
const Query = sdk.Query;
`

### 👍 Expected behavior

Query class gets imported and can be used in database requests.

### 👎 Actual Behavior

Error: Property 'Query' does not exist on type 'typeof import("node-appwrite")'.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite 0.12

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@vladmit3 is this still a problem or can it be closed?
