### ISSUE TITLE
Add CURL Templates to the SDK generator

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#37]
This is not really a new SDK feature request. We need CURL templates to help us auto-generate code examples that uses the REST API **DIRECTLY** with plain HTTP and no SDK.

This is useful for users who don't want to add an SDK dependency or users who are using platforms which we don't yet support.

This issue is associated to the issue by @Joe118: https://github.com/appwrite/appwrite/issues/314

**Comment by PedroCisnerosSantana** [comment]
@eldadfux Assign me this issue, I'm already working on it

**Comment by PineappleIOnic** [comment]
If this isn't being worked on by @PedroCisnerosSantana I would like to take it on if that wouldn't be any issue

**Comment by PedroCisnerosSantana** [comment]
> If this isn't being worked on actively by @PedroCisnerosSantana I would like to take it on if that wouldn't be any issue

No problem for me, if @eldadfux agrees 😉

**Comment by eldadfux** [comment]
@PineappleIOnic sure no problem. I'll just mention again this can also be implemented as HTTP examples and not necessarily with CURL

**Comment by abnegate** [comment]
Closing as added in 0.29.0
