### ISSUE TITLE
Add Deno Templates to the SDK generator

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#39]
We need help adding Deno [https://github.com/denoland/deno] templates to this project to allow easy generation of a Deno SDK for the Appwrite server.

Deno is starting to get a lot of traction in the community and this could be a good timeframe to introduce a Deno SDK for backend integration with the Appwrite API and upcoming cloud function service.

We already have templates for TypeScript, I'm not sure if this is enough to support Deno or we should extend them for Deno specific modules like interacting with files or HTTP calls. Any feedback on this will also be helpful.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

**Comment by Almoullim** [comment]
Just leaving this here for anyone following this issue;

I've been working on this here https://github.com/appwrite/sdk-generator/pull/40, some features still in the work. If you would like to offer your help you can contact me or @eldadfux here or through the [discord server](https://discord.com/invite/GSeTUeA)

**Comment by eldadfux** [comment]
Version 0.0.2 of Deno SDK has been released with some bug fixed: https://github.com/appwrite/sdk-for-deno

**Comment by eldadfux** [comment]
Closing issue. Deno SDK is out. The beta version seems to be pretty stable, we might be able to release v1.0 soon.
