### ISSUE TITLE
Add Swift support

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#4]
Add Swift templates to allow easy generation of Swift SDKs for iOS, macOS and other platform that rely on the language.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

**Comment by lbm** [comment]
If this isn't being worked on, I'd be happy to give it a try @eldadfux.

**Comment by eldadfux** [comment]
@lbm This would be great! This is one of our most requested features and we have been looking for a Swift contributor for quite some time now. I would be happy to assist with any question here or on our Discord server (https://discord.gg/GSeTUeA). Feel free to reach out!

**Comment by lbm** [comment]
No worries, I’ll fork it and start looking into it as soon as possible. I’ll join the discord then too 🙂

**Comment by armino-dev** [comment]
Hi guys, I hope you don't mind. I had some spare time and made the first version of the Swift SDK generator
