### ISSUE TITLE
JavaScript Client SDK ES6 Module Support

### ISSUE THREAD

**Issue by rushsteve1** [appwrite/sdk-generator#41]
Supporting the more modern ES6 Module syntax would be a great addition and would natively support Node, Deno, and the Browsers.

[Rollup has a great write-up](https://github.com/rollup/rollup/wiki/ES6-modules) on why ES6 modules are better, and their [`pkg.module` page](https://github.com/rollup/rollup/wiki/pkg.module) also gives some more context and benefits of ES6 modules.

This is related to #39 and #40, but is specifically about ES6 modules, which are fully supported by TypeScript and Deno. So a possibility could be to replace the existing JavaScript SDK with the TypeScript one.

**Comment by Almoullim** [comment]
But we will have to drop support for older node versions

**Comment by Almoullim** [comment]
if we do this, we'll have to add a build step to continue supporting older versions of node

**Comment by eldadfux** [comment]
Closing for now. If anyone would like to help with a PR, I'll re-open the issue.
