### ISSUE TITLE
Add missing docs templates for Ruby/Java

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#42]
Add missing twig templates for docs examples for Ruby & Java. This are the code examples that we use for code snippets at: https://appwrite.io/docs

Example template (Node.js):
https://github.com/appwrite/sdk-generator/blob/97cb12c9c187a42a545060c324b0960c99582893/templates/node/docs/example.md.twig

**Comment by eldadfux** [comment]
I have added examples for ruby, now available on master.

**Comment by ng29** [comment]
Hey Eldad,

Can i take this one for Java to contribute in Hactoberfest :) ?

**Comment by eldadfux** [comment]
@ng29 go for it 👍 

You can also join our Discord server if you have any questions: https://appwrite.io/discord
