### ISSUE TITLE
Add a consistent user-agent header to all the SDKs

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#48]
We need to add a consistent user-agent header that will be sent with any HTTP request made by any of our SDKs HTTP clients.

All the user-agent headers should follow the same standard to allow us to parse them easily on the server side in order to get info about the end client platform name, version, and technology.

Any suggestion for the header format will be appreciated.

**Comment by stnguyen90** [comment]
@eldadfux can this be closed now?

**Comment by stnguyen90** [comment]
@lohanidamodar, can this be closed now?

**Comment by lohanidamodar** [comment]
Closing as this is now merged. We can reopen separate issue if we want any further enhancements.
