### ISSUE TITLE
🚀 Feature: Add function variables to appwrite.json

### ISSUE THREAD

**Issue by yaakov123** [appwrite/sdk-generator#525]
### 🔖 Feature description

As far as I can tell, the `appwrite.json` file is there to help with keeping dev/prod environments consistent (at least that's how I use it).

One thing that is missing for me is when the object that describes a function is generated in the file it's missing the variables property. Right now, if I would like to use the `appwrite deploy function` command, I would have to manually enter the environment variables in the Appwrite Console.

This is especially painful when creating many functions which require the APPWRITE_FUNCTION_ENDPOINT, APPWRITE_API_KEY variables.

If I have several hundred functions, this process isn't scalable.

### 🎤 Pitch

I'd like to add a field to the `appwrite.json->function` object which contains the variables that the function requires.

When I look through the code, it seems that the SDK retrieves the variables via the API and then deploys it with those same variables. It seems like it should be pretty trivial to add an option for upserting variables that exist in the function config.

I suppose the only quirk here is that variables that the user defined via the console would not show up in the config file, but as they say - "perfection is the enemy of good"

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@yaakov123, thanks for raising this issue! 🙏 Our intention with:

https://github.com/appwrite/sdk-for-cli/blob/d34c18412fb1d508546e7c686496d30337e4b924/lib/commands/deploy.js#L190-L198

was to ensure variables like secrets set in the Appwrite Console don't get wiped and become lost so I don't think we would change it to update the server with values in the appwrite.json.

Perhaps what we can do to improve things is to only create the variable on the server if it doesn't exist yet. How does that sound?

**Comment by stnguyen90** [comment]
@yaakov123, anything else you need or can this be closed?

**Comment by yaakov123** [comment]
I think this is good for now and can be closed.
