### ISSUE TITLE
🚀 Feature: WeChat mini program sdk

### ISSUE THREAD

**Issue by sunnycat1991** [appwrite/sdk-generator#558]
### 🔖 Feature description

I suggest you also refer to the development of wechat cloud
There are million developers need WeChat mini program sdk.

### 🎤 Pitch

Now,JavaScript sdk can not be used to WeChat mini program  ,when i install it,throw some wrong.
WeChat have millions developers and billion users daily 

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@sunnycat1991 could you please provide details on what the error is that's thrown?

**Comment by sunnycat1991** [comment]
> 

Compiling miniprogram_npm/tr46   is very difficult

**Comment by stnguyen90** [comment]
> <img alt="屏幕截图 2022-09-23 091953" width="1289" src="https://user-images.githubusercontent.com/18379990/191876816-1e36be0f-9ee7-46e8-a8ba-1689f89a895a.png">
> 
> >
> > @sunnycat1991您能否提供有关引发的错误的详细信息？
> 
> install 1-2mins tips:Compiling miniprogram_npm/tr46/index.js ...
> 
> then throw "Error: module 'miniprogram_npm/combined-stream/util.js' is not defined, require args is 'util'"

@sunnycat1991 interesting...I don't see anything related to Appwrite in this output, though. 🧐

**Comment by sunnycat1991** [comment]
> 

The tr46 file is included in the AppWrite installation package

**Comment by sunnycat1991** [comment]
> > 
> 
> The tr46 file is included in the AppWrite installation package


The tr46 file is included in the AppWrite installation package

**Comment by sunnycat1991** [comment]
In addition, if you can open the website of China, this is tencent's WeChat of front from server-side development projects, including database, storage, function, and also involves complex database, speaking, reading and writing, database security rules, at the same time support aggregation query and pipelining, database field support location, time, etc., also supports atomic operations.

It is a Chinese website, the development document, I do not know whether you can open, whether you can read clearly.

https://developers.weixin.qq.com/miniprogram/dev/wxcloud/reference-sdk-api/database/Collection.html

**Comment by sunnycat1991** [comment]
> > The tr46 file is included in the AppWrite installation package
> 
> The tr46 file is included in the AppWrite installation package

Sorry，combined-stream file is included in the AppWrite

**Comment by sunnycat1991** [comment]
WeChat Cloud is not an open source project. At the same time, it does not support web and app development well. It is mainly aimed at WeChat applets. Now the charge price is very high. Millions of developers are fleeing to find alternative products.
> > 
> > install 1-2mins tips:Compiling miniprogram_npm/tr46/index.js ...
> > then throw "Error: module 'miniprogram_npm/combined-stream/util.js' is not defined, require args is 'util'"
> 
> @sunnycat1991 interesting...I don't see anything related to Appwrite in this output, though. 🧐

WeChat Cloud is not an open source project. At the same time, it does not support web and app development well. It is mainly aimed at WeChat applets. Now the charge price is very high. Millions of developers are fleeing to find alternative products.

**Comment by stnguyen90** [comment]
@sunnycat1991, although you can't use the SDK, you should be able to manually make API calls to Appwrite. Just make sure to set the X-appwrite-project header.
