### ISSUE TITLE
Support up to date dependencies

### ISSUE THREAD

**Issue by letsdev19** [appwrite/sdk-generator#595]
Please update dependencies for appwrite flutter package. It has 8 dependencies that are not up to date and is now conflicting with some packages that I need to use for my app, specifically **package_info_plus** which is at v3.0.2 and appwrite only support up to v1.4.3.

![Screenshot 2022-12-03 at 14 15 36](https://user-images.githubusercontent.com/47488347/205440531-a7392c0b-7fca-4cb1-b605-d84d9b81cbe9.png)

**Comment by lohanidamodar** [comment]
hey @letsdev19, we are updating the package soon, however for now you can try to use `dependency_overrides` to override the conflicting dependencies and see if it works

**Comment by lohanidamodar** [comment]
@letsdev19 Version 8.2.1 (https://pub.dev/packages/appwrite/versions/8.2.1) should resolve this. Feel free to re-open if there are issues.
