### ISSUE TITLE
Invalid syntax for Comment in python

### ISSUE THREAD

**Issue by Better-Boy** [appwrite/sdk-generator#60]
In all of the docs examples, `//` is used for comments which result in a syntax error. 

I have corrected those for avatars in my clone of this repo - https://github.com/Better-Boy/sdk-for-python

And I have also reformatted the code for readability purposes. If the changes regarding avatars are fine, I'll do the same for the rest of the examples and open a PR

Also included a `.gitignore` file.

As this is a read-only repo, I have no permission to pull a PR.

**Comment by eldadfux** [comment]
Seems like this issue was already fixed and we just need to deploy a new version of appwrite.io.

You can submit a PR against the Python example code twig template for any code readability improvements:
https://github.com/appwrite/sdk-generator/blob/master/templates/python/docs/example.md.twig
