### ISSUE TITLE
🐛 Bug Report: Homebrew CLI Install Isn't Working 1.2.x

### ISSUE THREAD

**Issue by gewenyu99** [appwrite/sdk-generator#608]
### 👟 Reproduction steps

When you follow steps in docs to install CLI via Homebrew, it will error out like the following:

![](https://cdn.discordapp.com/attachments/1068557906418602205/1068557907295223838/Screenshot_2023-01-27_at_10.46.05_AM.png)

### 👍 Expected behavior

Should install.

### 👎 Actual Behavior

Does not install.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

MacOS

### 🧱 Your Environment

1.2.x

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
Related issue: https://github.com/appwrite/sdk-for-cli/issues/71

**Comment by lohanidamodar** [comment]
@gewenyu99 @stnguyen90 is this still an issue?

**Comment by gewenyu99** [comment]
Closing, seems fixed @lohanidamodar
