### ISSUE TITLE
Need advice for a pull request

### ISSUE THREAD

**Issue by MoskalykA** [appwrite/sdk-generator#635]
Hi there,
I'd like to make a pull request, since it's my first one here I'd like your advice not to make a mistake.

I would like to make these changes:
![image](https://user-images.githubusercontent.com/100430077/227770567-0eb0d6cf-65ef-421f-bab5-8f5c54881871.png)

What do you think? I consider this as a slight optimization according to this article, is this a good idea?

**Comment by joeyouss** [comment]
Hi, thank you for your question.
I am sorry but which article are you referring to? Can you please backlink it once so I can take a look?

**Comment by MoskalykA** [comment]
> Hi, thank you for your question. I am sorry but which article are you referring to? Can you please backlink it once so I can take a look?

Yeah, https://www.builder.io/blog/double-equal-vs-triple-equal

**Comment by joeyouss** [comment]
Please consider opening a PR and we will review it.
Also, please make sure to follow the issue-template we have for opening issues since it helps us understand better!

**Comment by MoskalykA** [comment]
> Please consider opening a PR and we will review it. Also, please make sure to follow the issue-template we have for opening issues since it helps us understand better!

Ok thanks, sorry for the inconvenience
