### ISSUE TITLE
🐛 Bug Report: Server sdk for node deleteFile api delete storage bucket instead of file.

### ISSUE THREAD

**Issue by usamashafiqs** [appwrite/sdk-generator#638]
### 👟 Reproduction steps

Server sdk for node ```deleteFile``` api delete storage bucket if file ID had empty string as parameter.
It should throw exception if file ID had empty string.
```ts
try {
    const res = await SDK.storage.deleteFile('BucketID', '');
    console.log(res);
} catch (e) {
    if (e instanceof AppwriteException) {
        console.log(e.message);
    }
    console.log(e);
}
```

### 👍 Expected behavior

It should throw exception if file ID had empty string provided instead of file ID.

### 👎 Actual Behavior

Server sdk for node deleteFile api delete storage bucket if file ID had empty string as parameter.

### 🎲 Appwrite version

Different version (specify in environment)

### 💻 Operating system

Linux

### 🧱 Your Environment

Appwrite version 1.2.1
node-appwrite version 8.2.0

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi 👋🏻 Thanks for reporting, I'll discuss with the team to come up with a solution. I'll keep you posted

**Comment by stnguyen90** [comment]
Closing as this has been addressed in Appwrite so that the API call doesn't get matched to the bucket endpoint.
