### ISSUE TITLE
Are Python SDK API calls truly Asynchronous?

### ISSUE THREAD

**Issue by Nibba2018** [appwrite/sdk-generator#65]
While using the following syntax to call appwrite's methods:
```python
async def create_collection():
    database = Database(client)
    print("Running Create Collection API")
    response = await database.create_collection(...)
    collectionId = response['$id']
    print(response)
```
leads to the following error:
`object dict can't be used in 'await' expression`

After some googling I found that the sdk class needs to implement `__await__()` dunder function to make it `awaitable` and hence asynchronous.

I also tried a different implementation [here](https://github.com/appwrite/playground-for-python/pull/22) by removing `await` before the sdk method call.
After running some tests I found that the execution time and order of execution were similar to that of the synchronous one. So I am not really sure if its truly asynchronous. Any thoughts regarding this issue? or am I doing something wrong?

**Comment by TorstenDittmann** [comment]
Closing this in favor of https://github.com/appwrite/sdk-for-python/issues/26
