### ISSUE TITLE
🚀 Feature: Allow user-defined fetch function for web sdk

### ISSUE THREAD

**Issue by SilverMira** [appwrite/sdk-generator#652]
### 🔖 Feature description

Currently, the web SDK is importing and using `fetch` from `cross-fetch`  inside `Client.call`, is it possible to introduce a `Client.setFetch(fetchFn)` for users to provide the implementation to use?

I would be happy to create a PR for this feature

### 🎤 Pitch

When using appwrite with SvelteKit and SSR, there's a need to use SvelteKit's special fetch function on page load. This special fetch function provides additional functionalities as described [here](https://kit.svelte.dev/docs/load#making-fetch-requests). One of them being ability of reusing what the server has fetched from appwrite instead of refetching them on the client during hydration.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by joeyouss** [comment]
Hi
This is a cool feature, you could definitely try making a PR, but it would be to our SDK-generator, which can be a bit hard to do.

**Comment by SilverMira** [comment]
Hi, I have created the PR, hope everything goes smoothly 🚀
