### ISSUE TITLE
🐛 Bug Report: failing to generate SDKs using example.php

### ISSUE THREAD

**Issue by Ananya2001-an** [appwrite/sdk-generator#666]
### 👟 Reproduction steps

After installing dependencies using composer ran this:

```bash
docker run --rm -v $(pwd):/app -w /app php:7.4-cli php example.php
```

### 👍 Expected behavior

On running the above docker command we should get a dir called "examples" in the root with all the SDKs. 

### 👎 Actual Behavior

![image](https://github.com/appwrite/sdk-generator/assets/55504616/d3e11344-ee7a-4785-9ef3-d9b694a801b0)

The examples dir is not getting created because of the failing curl request... moreover echoeing the success message at the end is misleading, so should put it inside a condition or something

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Windows

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by lohanidamodar** [comment]
@Ananya2001-an Please try using php 8.1
```
docker run --rm -v $(pwd):/app -w /app php:8.1-cli php example.php
```

**Comment by Ananya2001-an** [comment]
thanks @lohanidamodar it works now! Maybe you should update the docs here: https://github.com/appwrite/sdk-for-cli/blob/b4619977eb95ca6650aa5291eb6a26d6bfa46eda/README.md?plain=1#L225

**Comment by lohanidamodar** [comment]
> thanks @lohanidamodar it works now! Maybe you should update the docs here: [appwrite/sdk-for-cli@`b461997`/README.md?plain=1#L225](https://github.com/appwrite/sdk-for-cli/blob/b4619977eb95ca6650aa5291eb6a26d6bfa46eda/README.md?plain=1#L225)

Thanks, will do.
