### ISSUE TITLE
Missing required params in flutter doc examples

### ISSUE THREAD

**Issue by Glide7** [appwrite/sdk-generator#69]
When you replace hostname, projectId and collection Id  it wont work.
![unknown](https://user-images.githubusercontent.com/51369094/100535915-b5c99d80-3225-11eb-8491-cbb7c503fba0.png)

**Comment by stnguyen90** [comment]
@Glide7, is this still a problem? It seems to work based on the playground for flutter sample. 

https://github.com/appwrite/playground-for-flutter/blob/master/lib/main.dart
