### ISSUE TITLE
Add Ruby Templates to the SDK generator

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#7]
We need help adding Ruby templates to this project to allow easy generation of Ruby SDKs for the Appwrite server. We already have some templates ready for Ruby but we still need to test them and complete the SDK features checklist to provide full support for developers.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

**Comment by asha15** [comment]
@eldadfux  Shall i try this sir?

**Comment by eldadfux** [comment]
@asha15 that will be great! tAs I said, the best way to start is by reading the contribution guide:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

You can reach me out on Gitter for any question.

**Comment by eldadfux** [comment]
I have just updated the ruby templates to have better support for the required SDKs features. We are also working on adding cross-platform tests for all SDK, which helps us have better awareness of SDK support status.

Just published our Appwrite SDK beta version on rubygems.org
https://rubygems.org/gems/appwrite

@asha15 it will be great if you or anyone else could code review the package and let me know if anything is missing, or if we could make this SDK more native to the Ruby ecosystem.

**Comment by eldadfux** [comment]
Closing this in favour of: https://github.com/appwrite/appwrite/issues/419

For anyone following this topic, Ruby templates have been added, but lack support for file uploading and still has some known issue we need to address. If anyone would like to help on this, please contact me.
