### ISSUE TITLE
🐛 Bug Report: Python SDK Local variable path referenced before assignament

### ISSUE THREAD

**Issue by gepd** [appwrite/sdk-generator#704]
### 👟 Reproduction steps

![image](https://github.com/appwrite/sdk-generator/assets/7091609/f4d7cce0-5a33-4f00-9e87-271da380d77a)

Image got from https://discord.com/channels/564160730845151244/1146544839614287923

### 👍 Expected behavior

run `createDocument`

### 👎 Actual Behavior

It returns error `Local variable path referenced before assignament`

Looking the code https://github.com/appwrite/sdk-for-python/blob/master/appwrite/services/databases.py#L924 path var is called `api_path` but referenced as `path` later in the code: https://github.com/appwrite/sdk-for-python/blob/master/appwrite/services/databases.py#L938-L939

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by brian-o-mars** [comment]
This is also repeated in other function definitions too.

**Comment by joeyouss** [comment]
Thank you so much for opening this issue @gepd . I have passed to my team and as soon as we have some feedback on this I will let you know ASAP.

**Comment by versun** [comment]
@joeyouss 
I've found the reason.
In the file [databases.py](https://github.com/appwrite/sdk-for-python/blob/f24f9b2dcd8f8fa1a5608a4191e5f016067af51c/appwrite/services/databases.py), the original variable "path" was changed to "api_path"(Last commit)
but the modification was only made in the definition and not in all the places where it is called. 
![2023-09-01](https://github.com/appwrite/sdk-generator/assets/2398708/9c205f54-b929-4c06-a8da-9bb72cc3f052)

As a result, all functions related to databases will fail
