### ISSUE TITLE
🐛 Bug Report: Node SDK typescript typing mismatch

### ISSUE THREAD

**Issue by YandiBanyuKarimaWaly** [appwrite/sdk-generator#726]
### 👟 Reproduction steps

Assume using pnpm package manager:

1. `pnpm init`
2. `pnpm add -D typescript @types/node`
3. `pnpm add node-appwrite`
4. `pnpm tsc --init`
5. Now, create a new file `index.ts` with this content:
```typescript
import { Role } from 'node-appwrite'

Role.label('hello world')
```
6. `pnpm tsc index.ts`

Then the error shows up:
`index.ts:3:6 - error TS2339: Property 'label' does not exist on type 'typeof Role'.`

### 👍 Expected behavior

Role.label is defined (I look at the generated .js file, it is there) so it should be on the index.d.ts file

### 👎 Actual Behavior

Role.label is not on the index.d.ts file

### 🎲 Appwrite version

Version 0.11.x

### 💻 Operating system

Linux

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by stnguyen90** [comment]
@YandiBanyuKarimaWaly thanks for raising this issue! 🙏🏼 It looks like it's missing from our template:

https://github.com/appwrite/sdk-generator/blob/2069238e3a3b96ebf6359e8eca8caf4e37a1868c/templates/node/index.d.ts.twig#L204-L211
