### ISSUE TITLE
🚀 Feature: Upgrade flutter_web_auth_2 to version 3.0.0

### ISSUE THREAD

**Issue by mariomurrent-softwaresolutions** [appwrite/sdk-generator#731]
### 🔖 Feature description

Since the current appwrite flutter version 11.0.0 breaks the android build it would be nice to upgrade to flutter_web_auth_2 v.3.0.0

### 🎤 Pitch

It's probably just a library upgrade

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by ThexXTURBOXx** [comment]
Related issue: https://github.com/ThexXTURBOXx/flutter_web_auth_2/issues/80
