### ISSUE TITLE
📚 Documentation: createPhoneSession() does not exist

### ISSUE THREAD

**Issue by dhonig-weizmann** [appwrite/sdk-generator#808]
### 💭 Description

In the page for phone authentication via sms: https://appwrite.io/docs/products/auth/phone-sms

The Dart code contains:
```
final sessionToken = await account.createPhoneSession(
    userId: ID.unique(),
    phone: '+14255550123'
);
```

In version 12.0.1, released 33 days ago, the function does not exist. createPhoneToken() is the closest function, and seems to perform the same action.

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by dhonig-weizmann** [comment]
This appears to be because this version of the plugin does not support this function. It would be great if it would be mentioned that this is in Flutter plugin 11.0.1 and not the latest version.

**Comment by stnguyen90** [comment]
Yes, we have plans to improve versioning on our docs. For now, I'm going to close this issue.
