### ISSUE TITLE
Add C# Templates to the SDK Generator

### ISSUE THREAD

**Issue by eldadfux** [appwrite/sdk-generator#9]
We need help adding C# templates to this project to allow easy generation of C# SDKs for Appwrite server.

A full guide on how to add new language support to the Appwrite SDK generator is located here:
https://github.com/appwrite/sdk-generator/blob/master/CONTRIBUTING.md

**Comment by Kerl1310** [comment]
I'd like to get involved with this

**Comment by eldadfux** [comment]
Hey @Kerl1310 that will be amazing! Please reach out to me on Gitter for any question or help!

**Comment by Joe118** [comment]
I can also help.

**Comment by Kerl1310** [comment]
Think this is finished, awaiting review

**Comment by Joe118** [comment]
Cool. Where can I take a peek?

**Comment by Joe118** [comment]
Actually I meant where can I take a look at the generated C# SDK for AppWrite lol

**Comment by eldadfux** [comment]
Hey @Kerl1310 were the c# files written manually or using the twig templates? If manually I can help creating the twig templates, just let me know.

Also, could you please add a snippet example to show how to init the SDK and make an HTTP call?

**Comment by eldadfux** [comment]
So there's some good news about this issue. @komemi have been working on it for the last few days and it seems close to a PR. We'll add more update to this issue when more progress is made.

**Comment by eldadfux** [comment]
The .NET SDK first *experimental* release is out: https://github.com/appwrite/sdk-for-dotnet we'd love help with testing!

All credits to @komemi and @TorstenDittmann for working on this! Great work guys!!
